### PR TITLE
Allow use of Pytorch 2x, Pandas 2x, and Numpy 1.26

### PR DESCRIPTION
**Pull request by bvanbreugel**
## Description
Allow installing Pytorch 2 and pandas 2. This solves four open issues #172, #171, #234 #245

## Affected Dependencies
Only removed restrictions on pytorch, numpy, and pandas versions

## How has this been tested?
Ran standard workflows

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/vanderschaarlab/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/vanderschaarlab/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [van der Schaar Lab Styleguide](https://github.com/vanderschaarlab/.github/blob/main/STYLEGUIDE.md)
- [x] I have labelled this PR with the relevant [Type labels](https://github.com/vanderschaarlab/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by bvanbreugel** [comment]
The problem of upgrading to Torch 2.x arises from the DP mechanism in CTGAN, and seems to be the Opacus library itself being incompatible. I don't know yet how to fix this---if anyone wants to contribute to this, please reach out.

**Comment by cynddl** [comment]
Thanks @bvanbreugel for opening this PR. We have been trying to use synthcity in our research, but the complex dependencies with old versions of PyTorch and Python is a nightmare. That's a shame.

Have you been able to make it work? Opacus 1.4 works with PyTorch 2.0 apparently.

**Comment by boegel** [comment]
Any updates on this?

We're also very interested to let synthcity support PyTorch 2.x

**Comment by robsdavis** [comment]
The dependency requirements have now been updated in #288

**Pull request closed without merging**
