### PR TITLE
Classification metric fix [type:bug]

### PR DESCRIPTION
**Pull request by bvanbreugel**
## Description
Ensures that when the task of a dataset is classification, we always use classification (and do not switch to R2). Minimal changes to the codebase. N.B. this is based off branch of PR #257.

## Affected Dependencies
None

## How has this been tested?
Standard fast tests

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/vanderschaarlab/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/vanderschaarlab/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [van der Schaar Lab Styleguide](https://github.com/vanderschaarlab/.github/blob/main/STYLEGUIDE.md)
- [x] I have labelled this PR with the relevant [Type labels](https://github.com/vanderschaarlab/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by bvanbreugel** [comment]
@robsdavis Do you know where this error comes from? It fails to load `plugin` from` plugin_goggle.py`, and I suspect this is a common issue (looking at some rather confusing definitions there)?

**Comment by bvanbreugel** [comment]
@robsdavis again, this doesn't seem to pass the tests just because of an HTTPError. Does this sound familiar to you?

**Comment by robsdavis** [comment]
The HTTPError is a transient connection issue. If you re-run it should work

**Comment by bvanbreugel** [comment]
@robsdavis Thanks. I don't think I have permission to re-run workflows (at least, I don't see the option where it should be). I've tried re-running a while ago by pushing a trivial comment, but again got the same HTTPS error. Could you re-run and see whether this is now fixed? Same for the other PR

**Review by robsdavis — APPROVED** [review]
LGTM!

**Pull request merged**
